name       : skaffold
version    : 0.11.0
release    : 1
source     :
    - https://github.com/GoogleContainerTools/skaffold/archive/v0.11.0.tar.gz : 253b7c15684e48cfbc90e002eb1dcb64f491f9fd5733fc7e015be212c48aaff3
license    : Apache-2.0
component  : programming.tools
summary    : Skaffold is a command line tool that facilitates continuous development for Kubernetes applications.
description: |
    Skaffold is a command line tool that facilitates continuous development for Kubernetes applications.
builddeps  :
    - golang
setup      : |
    export orgdir="src/github.com/GoogleContainerTools"
    export prodir="$orgdir/skaffold"
    mkdir -p bin pkg src $orgdir
    tar -xf $sources/v$version.tar.gz -C $orgdir
    mv $prodir-$version $prodir
build      : |
    export GOPATH="$workdir"
    cd src/github.com/GoogleContainerTools/skaffold
    %make_install
install    : |
    install -Dm00755 bin/skaffold $installdir/usr/bin/skaffold
